name: html_search
description: A package to quickly search though HTML.
version: 0.3.1
homepage: https://github.com/Ampless/html_search

environment:
  sdk: ^3.0.0

dependencies:
  html: ^0.15.0

dev_dependencies:
  lints: ^4.0.0
