name: html_search
description: A package to quickly search though HTML.
homepage: https://github.com/Ampless/html_search

version: 0.0.2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  html: ^0.14.0+4

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.4
