name: html_search
description: A package to quickly search though HTML.
version: 0.3.2
homepage: https://github.com/Ampless/html_search

environment:
  sdk: ^3.10.0

dependencies:
  html: ^0.15.0

dev_dependencies:
  lints: ^6.0.0
