name: html_search
description: A package to quickly search though HTML.
homepage: https://github.com/Ampless/html_search

version: 0.2.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  html: ^0.15.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.2
